# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadingdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dgLoading(object):
    def setupUi(self, dgLoading):
        dgLoading.setObjectName("dgLoading")
        dgLoading.resize(250, 100)
        dgLoading.setMaximumSize(QtCore.QSize(16777215, 150))
        self.verticalLayout = QtWidgets.QVBoxLayout(dgLoading)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(dgLoading)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lLoadingStatus = QtWidgets.QLabel(self.widget)
        self.lLoadingStatus.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lLoadingStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lLoadingStatus.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lLoadingStatus.setObjectName("lLoadingStatus")
        self.horizontalLayout.addWidget(self.lLoadingStatus)
        self.verticalLayout.addWidget(self.widget)
        self.dgButtons = QtWidgets.QDialogButtonBox(dgLoading)
        self.dgButtons.setOrientation(QtCore.Qt.Horizontal)
        self.dgButtons.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.dgButtons.setObjectName("dgButtons")
        self.verticalLayout.addWidget(self.dgButtons)

        self.retranslateUi(dgLoading)
        self.dgButtons.accepted.connect(dgLoading.accept)
        self.dgButtons.rejected.connect(dgLoading.reject)
        QtCore.QMetaObject.connectSlotsByName(dgLoading)

    def retranslateUi(self, dgLoading):
        _translate = QtCore.QCoreApplication.translate
        dgLoading.setWindowTitle(_translate("dgLoading", "Dialog"))
        self.lLoadingStatus.setText(_translate("dgLoading", "Loading Library..."))
